sudo: required

services:
    - docker

dist: xenial

language: python

python:
    - "3.7"

after_success:
    - test “$TRAVIS_BRANCH” = “master” && test "$TRAVIS_PULL_REQUEST" = "false" && sh .travis/deploy_heroku.sh
