from gradient_descents.classic_gradient_descent import classic_grad_descent
from gradient_descents.stochastic_gradient_descent import stochastic_grad_descent
from gradient_descents.momentum_gradient_descent import momentum_grad_descent
from gradient_descents.rmsprop_gradient_descent import rmsprop_grad_descent
from gradient_descents.adam_gradient_descent import adam_grad_descent